# Generated by Django 5.1.7 on 2025-04-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="like",
            name="like_either_post_or_comment",
        ),
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_like_per_user_post",
        ),
        migrations.RemoveConstraint(
            model_name="like",
            name="unique_like_per_user_comment",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "comment"), ("user", "post")},
        ),
    ]
