# Generated by Django 5.1.7 on 2025-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0003_remove_like_like_either_post_or_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subrabble",
            name="identifier",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
