# Generated by Django 5.1.7 on 2025-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0004_subrabble_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subrabble",
            name="identifier",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
