# Generated by Django 5.1.7 on 2025-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0008_alter_comment_parent_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subrabble",
            name="visibility",
            field=models.IntegerField(
                choices=[(1, "Public"), (2, "Private")], default=1
            ),
        ),
    ]
